### ISSUE TITLE
Use greenkeeper integration for automatic updating

### ISSUE THREAD

**Issue by 0x1ad2** [mschilling/codeheroes-dashboard#13]
Should be awesome if we could add https://greenkeeper.io/ to this repository, I'm currently using it on my public repositories, not sure what the costs might be.

**Comment by mschilling** [comment]
Would be great to see a working demo (in a separate `pull_request`?)

**Comment by 0x1ad2** [comment]
sure will implement, only need admin rights to do so.

**Comment by mschilling** [comment]
I've added the integration

<img width="752" alt="screenshot 2017-05-02 17 06 04" src="https://cloud.githubusercontent.com/assets/7045335/25624437/abf0ca4a-2f59-11e7-9e43-b6ecafafbbc2.png">

**Comment by 0x1ad2** [comment]
Greenkeeper is enabled and has run successful.
~ closed
