### ISSUE TITLE
Show repo @ commits of today

### ISSUE THREAD

**Issue by cassshh** [mschilling/codeheroes-dashboard#15]
In *Commits today*
Show which repo the commit has been pushed to.
**How it is now**
![old](https://cloud.githubusercontent.com/assets/10263056/25425280/c2536f92-2a6b-11e7-8010-a33bd6d2e95d.PNG)

**Feature request**
![new](https://cloud.githubusercontent.com/assets/10263056/25425308/d62d571c-2a6b-11e7-89d2-3f07de3319e6.PNG)

Maybe even show which branch?

**Comment by wwolters** [comment]
I like the idea!

Including the branch in the same style would probably often be too long.
![screen shot 2017-04-26 at 16 11 40](https://cloud.githubusercontent.com/assets/5948253/25438884/0fcd6712-2a9b-11e7-9d11-fa26e441f924.png)

**Comment by mschilling** [comment]
Repo name added :-)

<img width="398" alt="screenshot 2017-04-26 21 27 15" src="https://cloud.githubusercontent.com/assets/7045335/25452905/817a5470-2ac7-11e7-9938-ac496dddfbe9.png">
