### ISSUE TITLE
Build error using angular-cli

### ISSUE THREAD

**Issue by mschilling** [mschilling/codeheroes-dashboard#17]
When using `ng build`, the following build error occurs:

![screenshot 2017-04-28 08 37 50](https://cloud.githubusercontent.com/assets/7045335/25517173/6f81d658-2bee-11e7-8700-0d2a80f08d19.png)

`File to import not found or unreadable: ~@angular/material/core/theming/all-theme.`

How to reproduce: remove local `node_modules` folder and run `ng build`

Chances are we have to update one or more packages.

Help wanted ;-)

**Comment by mschilling** [comment]
Note: `master` build on travis is passing. So probably Travis is caching some older node modules.

**Comment by cassshh** [comment]
Fixed in https://github.com/mschilling/codeheroes-dashboard/commit/155318b4311e1da46b9f20a318eefd520488a0d8
