### ISSUE TITLE
Pre-Bootstrap loading screen

### ISSUE THREAD

**Issue by ArwinStrating** [mschilling/codeheroes-dashboard#22]
When opening coders.move4mobile.io a plain text "loading" appears in the upper left corner of the screen for a small amount of time. This might be replaced by a Pre-Bootstrapped loading screen?

**Comment by 0x1ad2** [comment]
@ArwinStrating u vraagt, wij draaien https://github.com/mschilling/codeheroes-dashboard/commit/ab8aad920438e40ab6b6e6bfa44e653a7041224f

**Comment by ArwinStrating** [comment]
Fixed by [ab8aad9](https://github.com/mschilling/codeheroes-dashboard/commit/ab8aad920438e40ab6b6e6bfa44e653a7041224f)

**Comment by mschilling** [comment]
Great job guys (@ArwinStrating and @0x1ad2)

To improve our core 'way of working', we should try to use PR's as much as possible. We should also check the assignees, or two people could be working on the same issue ;-) 😂 .  

I'll create a PR so we can get the pre-bootstrap to production.
